# Generated by Django 5.1.6 on 2025-02-13 19:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_courte', models.TextField(blank=True, max_length=300)),
                ('type_projet', models.CharField(choices=[('FOND', 'Fondamentaux'), ('CYBER', 'Cybersécurité'), ('BLOC', 'BlockChaine'), ('AR/VR', 'AR/VR'), ('IA', 'Intelligence Artificielle')], max_length=5)),
                ('taille_equipe', models.IntegerField(default=1)),
                ('remunere', models.BooleanField(default=False)),
                ('remuneration', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=11)),
                ('lien_github', models.URLField(blank=True)),
                ('technologies', models.JSONField(default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_archive', models.BooleanField(default=False)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('est_epingle', models.BooleanField(default=False)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_crees', to='users.user')),
                ('participants', models.ManyToManyField(blank=True, related_name='projets_rejoints', to='users.user')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
