# Generated by Django 5.1.6 on 2025-02-14 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='remunere',
            new_name='est_remunere',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_courte',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lien_github',
        ),
        migrations.RemoveField(
            model_name='project',
            name='remuneration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='project',
            name='taille_equipe',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_participants',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='project',
            name='statut_projet',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projets_participes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_projet',
            field=models.CharField(choices=[('CYBER', 'Cybersécurité'), ('WEB', 'Web Fullstack'), ('ARVR', 'AR/VR'), ('AI', 'Intelligence Artificielle'), ('BLOCKCHAIN', 'Blockchain'), ('DEMODAY', 'Demo Day')], max_length=20),
        ),
    ]
