# Generated by Django 5.1.6 on 2025-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_remunere_project_est_remunere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_courte',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
