# Generated by Django 5.1.6 on 2025-02-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_description_courte'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='est_projet_entreprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='remuneration_par_personne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la rémunération par personne (en €)', max_digits=10, null=True),
        ),
    ]
