# Generated by Django 5.1.6 on 2025-02-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_est_projet_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'ordering': ['-date_creation']},
        ),
    ]
