# Generated by Django 5.1.6 on 2025-02-17 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_candidature_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=list, help_text='Les technologies ne sont pas obligatoires', null=True),
        ),
    ]
