# Generated by Django 4.2.7 on 2025-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.CharField(default='CODE', max_length=50, unique=True),
        ),
    ]
