# Collect all skills from various categories into a single list
ALL_SKILLS = [
    # Programming Languages
    ('ABAP', 'ABAP'),
    ('ADA', 'Ada'),
    ('AGILE', 'Agile'),
    ('ALPINE', 'Alpine.js'),
    ('AMQP', 'AMQP'),
    ('ANDROID', 'Android'),
    ('ANGULAR', 'Angular'),
    ('ANSIBLE', 'Ansible'),
    ('APACHE', 'Apache'),
    ('APACHE_AIRFLOW', 'Apache Airflow'),
    ('APACHE_SPARK', 'Apache Spark'),
    ('APOLLO', 'Apollo'),
    ('APP_ENGINE', 'Google App Engine'),
    ('APPWRITE', 'Appwrite'),
    ('ASANA', 'Asana'),
    ('ASPNET', 'ASP.NET'),
    ('ASPNET_CORE', 'ASP.NET Core'),
    ('ASPNET_MVC', 'ASP.NET MVC'),
    ('ASSEMBLY', 'Assembly'),
    ('AUTH0', 'Auth0'),
    ('AWS', 'AWS'),
    ('AXURE', 'Axure'),
    ('AZURE', 'Microsoft Azure'),
    ('AZURE_DEVOPS', 'Azure DevOps'),
    ('AZURE_FUNCTIONS', 'Azure Functions'),
    # B
    ('BABEL', 'Babel'),
    ('BACKBONE', 'Backbone.js'),
    ('BAMBOO', 'Bamboo'),
    ('BASH', 'Bash'),
    ('BDD', 'Behavior-Driven Development'),
    ('BIG_QUERY', 'Google BigQuery'),
    ('BIGCOMMERCE', 'BigCommerce'),
    ('BITBUCKET', 'Bitbucket'),
    ('BLOCKCHAIN', 'Blockchain'),
    ('BOOTSTRAP', 'Bootstrap'),
    ('BULMA', 'Bulma'),
    ('BUNTJS', 'Bun'),
    # C
    ('C', 'C'),
    ('CADDY', 'Caddy'),
    ('CakePHP', 'CakePHP'),
    ('CAPACITOR', 'Capacitor'),
    ('CASSANDRA', 'Cassandra'),
    ('CATALYST', 'Catalyst'),
    ('CELERY', 'Celery'),
    ('CHAI', 'Chai'),
    ('CHAKRA_UI', 'Chakra UI'),
    ('CHART_JS', 'Chart.js'),
    ('CHEF', 'Chef'),
    ('CI_CD', 'CI/CD'),
    ('CIRCLECI', 'CircleCI'),
    ('CLICKHOUSE', 'ClickHouse'),
    ('CLOJURE', 'Clojure'),
    ('CLOUD_FUNCTIONS', 'Cloud Functions'),
    ('CLOUD_STORAGE', 'Cloud Storage'),
    ('CLOUDFLARE', 'Cloudflare'),
    ('CLOUDFRONT', 'AWS CloudFront'),
    ('COBOL', 'COBOL'),
    ('COCKROACHDB', 'CockroachDB'),
    ('CODEQL', 'CodeQL'),
    ('CONFLUENCE', 'Confluence'),
    ('CONSUL', 'HashiCorp Consul'),
    ('CONTENTFUL', 'Contentful'),
    ('CORDOVA', 'Cordova'),
    ('COSMOS_DB', 'Cosmos DB'),
    ('COUCHDB', 'CouchDB'),
    ('CPP', 'C++'),
    ('CQRS', 'CQRS'),
    ('CRYSTAL', 'Crystal'),
    ('CSHARP', 'C#'),
    ('CSS', 'CSS'),
    ('CUCUMBER', 'Cucumber'),
    ('CYPRESS', 'Cypress'),
    # D
    ('D', 'D'),
    ('D3', 'D3.js'),
    ('DART', 'Dart'),
    ('DASK', 'Dask'),
    ('DATADOG', 'Datadog'),
    ('DATAOPS', 'DataOps'),
    ('DATOMIC', 'Datomic'),
    ('DDD', 'Domain-Driven Design'),
    ('DEBIAN', 'Debian'),
    ('DELPHI', 'Delphi'),
    ('DENO', 'Deno'),
    ('DEVOPS', 'DevOps'),
    ('DGRAPH', 'Dgraph'),
    ('DIGITALOCEAN', 'DigitalOcean'),
    ('DJANGO', 'Django'),
    ('DOCKER', 'Docker'),
    ('DOTNET', '.NET'),
    ('DPLYR', 'dplyr'),
    ('DRUPAL', 'Drupal'),
    ('DYNAMODB', 'AWS DynamoDB'),
    # E
    ('EC2', 'AWS EC2'),
    ('ECHO', 'Echo'),
    ('ECS', 'AWS ECS'),
    ('EKS', 'AWS EKS'),
    ('ELASTIC', 'Elastic Stack'),
    ('ELASTICSEARCH', 'Elasticsearch'),
    ('ELIXIR', 'Elixir'),
    ('EMBER', 'Ember.js'),
    ('EMOTION', 'Emotion'),
    ('ENZYME', 'Enzyme'),
    ('ERLANG', 'Erlang'),
    ('ESBUILD', 'esbuild'),
    ('ESLINT', 'ESLint'),
    ('EVENT_SOURCING', 'Event Sourcing'),
    ('EXPRESS', 'Express.js'),
    # F
    ('F_SHARP', 'F#'),
    ('FALCON', 'Falcon'),
    ('FASTAPI', 'FastAPI'),
    ('FASTCGI', 'FastCGI'),
    ('FAUNA', 'Fauna'),
    ('FIBER', 'Fiber'),
    ('FIGMA', 'Figma'),
    ('FINOPS', 'FinOps'),
    ('FIREBASE', 'Firebase'),
    ('FIRESTORE', 'Firestore'),
    ('FLASK', 'Flask'),
    ('FLASK_RESTFUL', 'Flask-RESTful'),
    ('FLUTTER', 'Flutter'),
    ('FORTRAN', 'Fortran'),
    ('FOUNDATION', 'Foundation'),
    ('FRAMER', 'Framer'),
    # G
    ('GAME_DEV', 'Game Development'),
    ('GATSBY', 'Gatsby'),
    ('GCP', 'Google Cloud'),
    ('GENSIM', 'Gensim'),
    ('GHOST', 'Ghost'),
    ('GIN', 'Gin'),
    ('GIT', 'Git'),
    ('GITHUB', 'GitHub'),
    ('GITHUB_ACTIONS', 'GitHub Actions'),
    ('GITLAB', 'GitLab'),
    ('GITOPS', 'GitOps'),
    ('GO', 'Go'),
    ('GRADLE', 'Gradle'),
    ('GRAFANA', 'Grafana'),
    ('GRAPHQL', 'GraphQL'),
    ('GRAYLOG', 'Graylog'),
    ('GROOVY', 'Groovy'),
    ('GRPC', 'gRPC'),
    ('GSAP', 'GSAP'),
    # H
    ('HADOOP', 'Hadoop'),
    ('HASKELL', 'Haskell'),
    ('HASURA', 'Hasura'),
    ('HEROKU', 'Heroku'),
    ('HOMEBREW', 'Homebrew'),
    ('HTML', 'HTML'),
    ('HUGGINGFACE', 'Hugging Face'),
    # I
    ('IAM', 'AWS IAM'),
    ('IBM_CLOUD', 'IBM Cloud'),
    ('IBMDB2', 'IBM Db2'),
    ('ILLUSTRATOR', 'Adobe Illustrator'),
    ('INFLUXDB', 'InfluxDB'),
    ('INSOMNIA', 'Insomnia'),
    ('INVISION', 'InVision'),
    ('IONIC', 'Ionic'),
    ('IOS', 'iOS'),
    ('IOT', 'IoT'),
    # J
    ('JAM_STACK', 'JAMStack'),
    ('JASMINE', 'Jasmine'),
    ('JAVA', 'Java'),
    ('JAVASCRIPT', 'JavaScript'),
    ('JENKINS', 'Jenkins'),
    ('JEST', 'Jest'),
    ('JETPACK_COMPOSE', 'Jetpack Compose'),
    ('JIRA', 'Jira'),
    ('JOOMLA', 'Joomla'),
    ('JQUERY', 'jQuery'),
    ('JSON_RPC', 'JSON-RPC'),
    ('JSF', 'JavaServer Faces'),
    ('JULIA', 'Julia'),
    ('JUNIT', 'JUnit'),
    ('JUPYTER', 'Jupyter'),
    ('JWT', 'JWT'),
    # K
    ('KAFKA', 'Apache Kafka'),
    ('KANBAN', 'Kanban'),
    ('KERAS', 'Keras'),
    ('KIBANA', 'Kibana'),
    ('KOA', 'Koa'),
    ('KOTLIN', 'Kotlin'),
    ('KOTLIN_MULTIPLATFORM', 'Kotlin Multiplatform'),
    ('KUBERNETES', 'Kubernetes'),
    # L
    ('LAMBDA', 'AWS Lambda'),
    ('LANGCHAIN', 'LangChain'),
    ('LARAVEL', 'Laravel'),
    ('LESS', 'Less'),
    ('LINODE', 'Linode'),
    ('LINUX', 'Linux'),
    ('LISP', 'Lisp'),
    ('LIT', 'Lit'),
    ('LOOKER', 'Looker'),
    ('LUA', 'Lua'),
    # M
    ('MACOS', 'macOS'),
    ('MAGENTO', 'Magento'),
    ('MARIADB', 'MariaDB'),
    ('MATERIAL_UI', 'Material-UI'),
    ('MATERIALIZE', 'Materialize CSS'),
    ('MATPLOTLIB', 'Matplotlib'),
    ('MATLAB', 'MATLAB'),
    ('MAUI', '.NET MAUI'),
    ('MAVEN', 'Maven'),
    ('MEMCACHED', 'Memcached'),
    ('MERCURIAL', 'Mercurial'),
    ('METABASE', 'Metabase'),
    ('MICROSERVICES', 'Microservices'),
    ('MICROSOFT_SQL', 'Microsoft SQL Server'),
    ('MLOPS', 'MLOps'),
    ('MOBX', 'MobX'),
    ('MOCHA', 'Mocha'),
    ('MOCKITO', 'Mockito'),
    ('MONGODB', 'MongoDB'),
    ('MQTT', 'MQTT'),
    ('MYSQL', 'MySQL'),
    # N
    ('NATS', 'NATS'),
    ('NATIVESCRIPT', 'NativeScript'),
    ('NEO4J', 'Neo4j'),
    ('NESTJS', 'NestJS'),
    ('NETLIFY', 'Netlify'),
    ('NEW_RELIC', 'New Relic'),
    ('NEXTJS', 'Next.js'),
    ('NGINX', 'Nginx'),
    ('NIGHTWATCH', 'Nightwatch'),
    ('NLTK', 'NLTK'),
    ('NODEJS', 'Node.js'),
    ('NOTION', 'Notion'),
    ('NPM', 'npm'),
    ('NUXTJS', 'Nuxt.js'),
    ('NUMPY', 'NumPy'),
    # O
    ('OAUTH', 'OAuth'),
    ('OBJECTIVEC', 'Objective-C'),
    ('OCAML', 'OCaml'),
    ('OPENCV', 'OpenCV'),
    ('OPENAI', 'OpenAI'),
    ('OPENAPI', 'OpenAPI'),
    ('OPENCART', 'OpenCart'),
    ('OPENSTACK', 'OpenStack'),
    ('ORACLE_CLOUD', 'Oracle Cloud'),
    ('ORACLE_DB', 'Oracle Database'),
    # P
    ('PANDAS', 'Pandas'),
    ('PARCEL', 'Parcel'),
    ('PASCAL', 'Pascal'),
    ('PERFORCE', 'Perforce'),
    ('PERL', 'Perl'),
    ('PHOENIX', 'Phoenix'),
    ('PHP', 'PHP'),
    ('PHPUNIT', 'PHPUnit'),
    ('PHOTOSHOP', 'Adobe Photoshop'),
    ('PLANETSCALE', 'PlanetScale'),
    ('PLAY', 'Play Framework'),
    ('PLAYWRIGHT', 'Playwright'),
    ('PLOTLY', 'Plotly'),
    ('PODMAN', 'Podman'),
    ('POSTCSS', 'PostCSS'),
    ('POSTGRESQL', 'PostgreSQL'),
    ('POSTMAN', 'Postman'),
    ('POWER_BI', 'Power BI'),
    ('POWERSHELL', 'PowerShell'),
    ('PREACT', 'Preact'),
    ('PRETTIER', 'Prettier'),
    ('PRESTASHOP', 'PrestaShop'),
    ('PRINCIPLE', 'Principle'),
    ('PRISMA', 'Prisma'),
    ('PROMETHEUS', 'Prometheus'),
    ('PROLOG', 'Prolog'),
    ('PROTO_IO', 'Proto.io'),
    ('PULUMI', 'Pulumi'),
    ('PUPPETEER', 'Puppeteer'),
    ('PUPPET', 'Puppet'),
    ('PWA', 'Progressive Web Apps'),
    ('PYTEST', 'Pytest'),
    ('PYTORCH', 'PyTorch'),
    ('PYTHON', 'Python'),
    # Q - (No entries with Q)
    # R
    ('R', 'R'),
    ('RABBITMQ', 'RabbitMQ'),
    ('RAILS', 'Ruby on Rails'),
    ('RDS', 'AWS RDS'),
    ('REACT', 'React'),
    ('REACTNATIVE', 'React Native'),
    ('REALM', 'Realm'),
    ('RECOIL', 'Recoil'),
    ('REDIS', 'Redis'),
    ('REDIS_DB', 'Redis Database'),
    ('REDUX', 'Redux'),
    ('REST', 'REST API'),
    ('ROLLUP', 'Rollup'),
    ('ROUTE53', 'AWS Route53'),
    ('RUBY', 'Ruby'),
    ('RUST', 'Rust'),
    # S
    ('S3', 'AWS S3'),
    ('SANITY', 'Sanity.io'),
    ('SAS', 'SAS'),
    ('SASS', 'Sass'),
    ('SCALA', 'Scala'),
    ('SCHEME', 'Scheme'),
    ('SCIKIT_LEARN', 'scikit-learn'),
    ('SCRUM', 'Scrum'),
    ('SCYLLADB', 'ScyllaDB'),
    ('SEABORN', 'Seaborn'),
    ('SELENIUM', 'Selenium'),
    ('SEMANTIC_UI', 'Semantic UI'),
    ('SENTRY', 'Sentry'),
    ('SERVERLESS', 'Serverless'),
    ('SHOPIFY', 'Shopify'),
    ('SHOPWARE', 'Shopware'),
    ('SINATRA', 'Sinatra'),
    ('SKETCH', 'Sketch'),
    ('SLIM', 'Slim'),
    ('SNYK', 'Snyk'),
    ('SNOWFLAKE', 'Snowflake'),
    ('SOAP', 'SOAP'),
    ('SOCKET_IO', 'Socket.IO'),
    ('SOLID', 'SOLID Principles'),
    ('SOLIDITY', 'Solidity'),
    ('SONARQUBE', 'SonarQube'),
    ('SONATYPE', 'Sonatype'),
    ('SPACY', 'spaCy'),
    ('SPLUNK', 'Splunk'),
    ('SPRING', 'Spring'),
    ('SQL', 'SQL'),
    ('SQLITE', 'SQLite'),
    ('SQUARESPACE', 'Squarespace'),
    ('STENCIL', 'Stencil'),
    ('STIMULUS', 'Stimulus'),
    ('STOMP', 'STOMP'),
    ('STORYBOOK', 'Storybook'),
    ('STORYBOOK_TEST', 'Storybook Testing'),
    ('STRAPI', 'Strapi'),
    ('STRUTS', 'Struts'),
    ('STYLED_COMPONENTS', 'styled-components'),
    ('STYLUS', 'Stylus'),
    ('SUPABASE', 'Supabase'),
    ('SUPERSET', 'Apache Superset'),
    ('SURREALDB', 'SurrealDB'),
    ('SVN', 'SVN'),
    ('SVELTE', 'Svelte'),
    ('SWAGGER', 'Swagger'),
    ('SWIFT', 'Swift'),
    ('SWIFT_UI', 'SwiftUI'),
    ('SYMFONY', 'Symfony'),
    # T
    ('TABLEAU', 'Tableau'),
    ('TAILWIND', 'Tailwind CSS'),
    ('TAURI', 'Tauri Mobile'),
    ('TDD', 'Test-Driven Development'),
    ('TEAMCITY', 'TeamCity'),
    ('TENSORFLOW', 'TensorFlow'),
    ('TERRAFORM', 'Terraform'),
    ('TESTING_LIBRARY', 'Testing Library'),
    ('TESTNG', 'TestNG'),
    ('TFS', 'Team Foundation Server'),
    ('THREE_JS', 'Three.js'),
    ('TIMESCALE', 'TimescaleDB'),
    ('TORNADO', 'Tornado'),
    ('TRAEFIK', 'Traefik'),
    ('TRAVIS', 'Travis CI'),
    ('TRELLO', 'Trello'),
    ('TYPESCRIPT', 'TypeScript'),
    # U
    ('UBUNTU', 'Ubuntu'),
    ('UNO_PLATFORM', 'Uno Platform'),
    ('UNREAL', 'Unreal Engine'),
    ('UX_PIN', 'UXPin'),
    # V
    ('VAGRANT', 'Vagrant'),
    ('VAULT', 'HashiCorp Vault'),
    ('VBA', 'VBA'),
    ('VBNET', 'VB.NET'),
    ('VERCEL', 'Vercel'),
    ('VERILOG', 'Verilog'),
    ('VHDL', 'VHDL'),
    ('VITE', 'Vite'),
    ('VITEST', 'Vitest'),
    ('VUEJS', 'Vue.js'),
    # W
    ('WEBASSEMBLY', 'WebAssembly'),
    ('WEBDRIVERIO', 'WebdriverIO'),
    ('WEBFLOW', 'Webflow'),
    ('WEBGL', 'WebGL'),
    ('WEBRTC', 'WebRTC'),
    ('WEBPACK', 'Webpack'),
    ('WEBSOCKET', 'WebSocket'),
    ('WEB3', 'Web3'),
    ('WINDOWS', 'Windows Server'),
    ('WIXCMS', 'Wix CMS'),
    ('WOOCOMMERCE', 'WooCommerce'),
    ('WORDPRESS', 'WordPress'),
    # X
    ('XAMARIN', 'Xamarin'),
    ('XD', 'Adobe XD'),
    ('XML_RPC', 'XML-RPC'),
    # Y
    ('YARN', 'Yarn'),
    # Z
    ('ZEND', 'Zend Framework'),
    ('ZEPLIN', 'Zeplin'),
    ('ZEROMQ', 'ZeroMQ'),
    ('ZIG', 'Zig'),
    ('ZUSTAND', 'Zustand'),
]

# Sort the list alphabetically by display name (second element in each tuple)
SKILL_CHOICES = sorted(ALL_SKILLS, key=lambda x: x[1])

# Dictionary mapping skill codes to their Font Awesome icons
SKILL_ICONS = {
    # Programming Languages
    'PYTHON': 'fab fa-python',
    'JAVASCRIPT': 'fab fa-js',
    'TYPESCRIPT': 'fab fa-js',
    'JAVA': 'fab fa-java',
    'CSHARP': 'fab fa-microsoft',
    'CPP': 'fas fa-code',
    'C': 'fas fa-code',
    'PHP': 'fab fa-php',
    'RUBY': 'fas fa-gem',
    'GO': 'fas fa-code-branch',
    'RUST': 'fas fa-gear',
    'SWIFT': 'fab fa-swift',
    'KOTLIN': 'fab fa-android',
    'PERL': 'fas fa-code',
    'SCALA': 'fas fa-code',
    'HASKELL': 'fas fa-code',
    'LUA': 'fas fa-moon',
    'R': 'fas fa-chart-line',
    'JULIA': 'fas fa-circle',
    'DART': 'fas fa-bullseye',
    'ELIXIR': 'fas fa-vial',
    'CLOJURE': 'fas fa-code',
    'ERLANG': 'fas fa-network-wired',
    'FORTRAN': 'fas fa-calculator',
    'GROOVY': 'fas fa-music',
    'LISP': 'fas fa-code',
    'OBJECTIVEC': 'fab fa-apple',
    'PASCAL': 'fas fa-code',
    'COBOL': 'fas fa-history',
    'ASSEMBLY': 'fas fa-microchip',
    'MATLAB': 'fas fa-square-root-alt',
    'POWERSHELL': 'fab fa-windows',
    'BASH': 'fas fa-terminal',
    'VBNET': 'fab fa-microsoft',
    'VERILOG': 'fas fa-microchip',
    'VHDL': 'fas fa-microchip',
    'ABAP': 'fas fa-cubes',
    'ADA': 'fas fa-code',
    'SAS': 'fas fa-table',
    'SCHEME': 'fas fa-code',
    'SOLIDITY': 'fab fa-ethereum',
    'SQL': 'fas fa-database',
    'ZIG': 'fas fa-bolt',
    'CRYSTAL': 'fas fa-gem',
    'F_SHARP': 'fab fa-microsoft',
    'VBA': 'fas fa-file-excel',
    'DELPHI': 'fas fa-code',
    'OCAML': 'fas fa-code',
    'PROLOG': 'fas fa-brain',
    'D': 'fas fa-code',

    # Web Frameworks & Libraries
    'DJANGO': 'fab fa-python',
    'FLASK': 'fab fa-python',
    'FASTAPI': 'fab fa-python',
    'RAILS': 'fas fa-train',
    'SPRING': 'fas fa-leaf',
    'LARAVEL': 'fab fa-laravel',
    'SYMFONY': 'fab fa-symfony',
    'EXPRESS': 'fab fa-node-js',
    'ASPNET': 'fab fa-microsoft',
    'ASPNET_MVC': 'fab fa-microsoft',
    'ASPNET_CORE': 'fab fa-microsoft',
    'NESTJS': 'fab fa-node-js',
    'DOTNET': 'fab fa-microsoft',
    'STRUTS': 'fab fa-java',
    'JSF': 'fab fa-java',
    'GIN': 'fas fa-cocktail',
    'ECHO': 'fas fa-code',
    'FIBER': 'fas fa-network-wired',
    'FLASK_RESTFUL': 'fab fa-python',
    'FALCON': 'fas fa-feather',
    'PHOENIX': 'fas fa-fire',
    'KOA': 'fab fa-node-js',
    'SINATRA': 'fas fa-hat-wizard',
    'CATALYST': 'fas fa-flask',
    'PLAY': 'fas fa-play',
    'CakePHP': 'fab fa-php',
    'SLIM': 'fab fa-php',
    'ZEND': 'fab fa-php',
    'TORNADO': 'fas fa-wind',

    # Frontend Frameworks & Libraries
    'REACT': 'fab fa-react',
    'NEXTJS': 'fab fa-react',
    'ANGULAR': 'fab fa-angular',
    'VUEJS': 'fab fa-vuejs',
    'NUXTJS': 'fab fa-vuejs',
    'SVELTE': 'fas fa-fire-alt',
    'GATSBY': 'fas fa-rocket',
    'EMBER': 'fas fa-fire',
    'BACKBONE': 'fas fa-spine',
    'JQUERY': 'fas fa-dollar-sign',
    'BOOTSTRAP': 'fab fa-bootstrap',
    'TAILWIND': 'fab fa-css3',
    'BULMA': 'fab fa-css3',
    'MATERIALIZE': 'fab fa-css3',
    'FOUNDATION': 'fas fa-building',
    'SEMANTIC_UI': 'fas fa-font',
    'MATERIAL_UI': 'fas fa-square',
    'CHAKRA_UI': 'fas fa-universal-access',
    'STYLED_COMPONENTS': 'fas fa-paint-brush',
    'EMOTION': 'fas fa-smile',
    'SASS': 'fab fa-sass',
    'LESS': 'fab fa-css3',
    'STYLUS': 'fab fa-css3',
    'HTML': 'fab fa-html5',
    'CSS': 'fab fa-css3-alt',
    'POSTCSS': 'fab fa-css3',
    'REDUX': 'fas fa-recycle',
    'MOBX': 'fas fa-sitemap',
    'RECOIL': 'fas fa-atom',
    'ZUSTAND': 'fas fa-box',
    'ALPINE': 'fas fa-mountain',
    'PREACT': 'fas fa-bolt',
    'LIT': 'fas fa-lightbulb',
    'STENCIL': 'fas fa-stamp',
    'SOLID': 'fas fa-layer-group',
    'STIMULUS': 'fas fa-bolt',
    'STORYBOOK': 'fas fa-book',
    'D3': 'fas fa-chart-bar',
    'CHART_JS': 'fas fa-chart-pie',
    'THREE_JS': 'fas fa-cube',
    'GSAP': 'fas fa-film',
    'WEBPACK': 'fas fa-box-open',
    'VITE': 'fas fa-bolt',
    'ESBUILD': 'fas fa-fast-forward',
    'PARCEL': 'fas fa-box',
    'ROLLUP': 'fas fa-scroll',
    'BABEL': 'fas fa-boxes',

    # Backend & Infrastructure
    'NODEJS': 'fab fa-node-js',
    'DENO': 'fas fa-dinosaur',
    'BUNTJS': 'fas fa-rabbit',
    'GRAPHQL': 'fas fa-project-diagram',
    'APOLLO': 'fas fa-rocket',
    'PRISMA': 'fas fa-database',
    'HASURA': 'fas fa-database',
    'REST': 'fas fa-exchange-alt',
    'GRPC': 'fas fa-stream',
    'OAUTH': 'fas fa-key',
    'JWT': 'fas fa-user-shield',
    'SWAGGER': 'fas fa-file-contract',
    'OPENAPI': 'fas fa-book',
    'RABBITMQ': 'fas fa-envelope',
    'KAFKA': 'fas fa-stream',
    'REDIS': 'fas fa-database',
    'CELERY': 'fas fa-tasks',
    'SOCKET_IO': 'fas fa-plug',
    'NGINX': 'fas fa-server',
    'APACHE': 'fas fa-server',
    'CADDY': 'fas fa-server',
    'TRAEFIK': 'fas fa-network-wired',
    'DOCKER': 'fab fa-docker',
    'KUBERNETES': 'fas fa-dharmachakra',
    'PODMAN': 'fas fa-cubes',
    'JENKINS': 'fab fa-jenkins',
    'TERRAFORM': 'fas fa-cubes',
    'ANSIBLE': 'fas fa-terminal',
    'PUPPET': 'fas fa-dog',
    'CHEF': 'fas fa-utensils',
    'PULUMI': 'fas fa-cloud-upload-alt',

    # Cloud Platforms & Services
    'AWS': 'fab fa-aws',
    'AZURE': 'fab fa-microsoft',
    'GCP': 'fab fa-google',
    'HEROKU': 'fas fa-cloud',
    'DIGITALOCEAN': 'fab fa-digital-ocean',
    'VERCEL': 'fas fa-v',
    'NETLIFY': 'fas fa-cloud-upload-alt',
    'FIREBASE': 'fas fa-fire',
    'CLOUDFLARE': 'fas fa-cloud',
    'LINODE': 'fas fa-server',
    'ORACLE_CLOUD': 'fas fa-cloud',
    'IBM_CLOUD': 'fab fa-ibm',
    'OPENSTACK': 'fas fa-cloud',
    'LAMBDA': 'fas fa-function',
    'S3': 'fas fa-hdd',
    'EC2': 'fas fa-server',
    'RDS': 'fas fa-database',
    'CLOUDFRONT': 'fas fa-globe',
    'DYNAMODB': 'fas fa-database',
    'ECS': 'fas fa-container-storage',
    'EKS': 'fas fa-dharmachakra',
    'IAM': 'fas fa-users-cog',
    'ROUTE53': 'fas fa-route',
    'AZURE_FUNCTIONS': 'fas fa-function',
    'AZURE_DEVOPS': 'fas fa-code-branch',
    'COSMOS_DB': 'fas fa-database',
    'APP_ENGINE': 'fas fa-rocket',
    'CLOUD_FUNCTIONS': 'fas fa-bolt',
    'BIG_QUERY': 'fas fa-database',
    'CLOUD_STORAGE': 'fas fa-hdd',
    'AUTH0': 'fas fa-lock',
    'SUPABASE': 'fas fa-database',

    # Databases
    'MYSQL': 'fas fa-database',
    'POSTGRESQL': 'fas fa-database',
    'MONGODB': 'fas fa-leaf',
    'SQLITE': 'fas fa-database',
    'CASSANDRA': 'fas fa-database',
    'MARIADB': 'fas fa-database',
    'ELASTICSEARCH': 'fas fa-search',
    'COUCHDB': 'fas fa-couch',
    'NEO4J': 'fas fa-project-diagram',
    'MICROSOFT_SQL': 'fab fa-microsoft',
    'ORACLE_DB': 'fas fa-database',
    'INFLUXDB': 'fas fa-chart-line',
    'FIRESTORE': 'fas fa-fire',
    'REALM': 'fas fa-globe',
    'DGRAPH': 'fas fa-project-diagram',
    'COCKROACHDB': 'fas fa-bug',
    'TIMESCALE': 'fas fa-clock',
    'SNOWFLAKE': 'fas fa-snowflake',
    'CLICKHOUSE': 'fas fa-mouse',
    'SURREALDB': 'fas fa-database',
    'FAUNA': 'fas fa-paw',
    'PLANETSCALE': 'fas fa-globe',
    'REDIS_DB': 'fas fa-database',
    'MEMCACHED': 'fas fa-memory',
    'SCYLLADB': 'fas fa-bolt',
    'APPWRITE': 'fas fa-pencil-alt',
    'DATOMIC': 'fas fa-atom',
    'IBMDB2': 'fab fa-ibm',

    # Version Control
    'GIT': 'fab fa-git-alt',
    'GITHUB': 'fab fa-github',
    'GITHUB_ACTIONS': 'fab fa-github',
    'GITLAB': 'fab fa-gitlab',
    'BITBUCKET': 'fab fa-bitbucket',
    'MERCURIAL': 'fas fa-code-branch',
    'SVN': 'fas fa-code-branch',
    'PERFORCE': 'fas fa-code-branch',
    'TFS': 'fab fa-microsoft',

    # Testing
    'JEST': 'fas fa-vial',
    'MOCHA': 'fas fa-coffee',
    'SELENIUM': 'fas fa-robot',
    'CYPRESS': 'fas fa-check-double',
    'JUNIT': 'fab fa-java',
    'PHPUNIT': 'fab fa-php',
    'PYTEST': 'fab fa-python',
    'JASMINE': 'fas fa-flower',
    'KARMA': 'fas fa-dharmachakra',
    'TESTNG': 'fab fa-java',
    'MOCKITO': 'fas fa-mask',
    'PLAYWRIGHT': 'fas fa-theater-masks',
    'PUPPETEER': 'fas fa-ghost',
    'WEBDRIVERIO': 'fas fa-car',
    'VITEST': 'fas fa-vial',
    'CUCUMBER': 'fas fa-seedling',
    'NIGHTWATCH': 'fas fa-moon',
    'STORYBOOK_TEST': 'fas fa-book',
    'TESTING_LIBRARY': 'fas fa-microscope',
    'CHAI': 'fas fa-mug-hot',
    'ENZYME': 'fas fa-flask',

    # Mobile Development
    'ANDROID': 'fab fa-android',
    'IOS': 'fab fa-apple',
    'REACTNATIVE': 'fab fa-react',
    'FLUTTER': 'fas fa-mobile-alt',
    'IONIC': 'fas fa-bolt',
    'XAMARIN': 'fab fa-microsoft',
    'CORDOVA': 'fas fa-mobile-alt',
    'CAPACITOR': 'fas fa-battery-full',
    'NATIVESCRIPT': 'fas fa-mobile-alt',
    'UNO_PLATFORM': 'fas fa-window-restore',
    'MAUI': 'fab fa-microsoft',
    'SWIFT_UI': 'fab fa-swift',
    'JETPACK_COMPOSE': 'fab fa-android',
    'KOTLIN_MULTIPLATFORM': 'fab fa-android',
    'TAURI': 'fas fa-window-maximize',

    # CMS & Ecommerce
    'WORDPRESS': 'fab fa-wordpress',
    'DRUPAL': 'fab fa-drupal',
    'JOOMLA': 'fab fa-joomla',
    'MAGENTO': 'fab fa-magento',
    'SHOPIFY': 'fab fa-shopify',
    'WOOCOMMERCE': 'fab fa-wordpress',
    'CONTENTFUL': 'fas fa-file-alt',
    'STRAPI': 'fas fa-boxes',
    'GHOST': 'fas fa-ghost',
    'SANITY': 'fas fa-check-double',
    'WIXCMS': 'fab fa-wix',
    'SQUARESPACE': 'fab fa-squarespace',
    'PRESTASHOP': 'fas fa-shopping-cart',
    'OPENCART': 'fas fa-shopping-cart',
    'WEBFLOW': 'fas fa-water',
    'BIGCOMMERCE': 'fas fa-shopping-bag',
    'SHOPWARE': 'fas fa-store',

    # Design & UI/UX
    'FIGMA': 'fab fa-figma',
    'SKETCH': 'fab fa-sketch',
    'ADOBE': 'fab fa-adobe',
    'PHOTOSHOP': 'fas fa-paint-brush',
    'ILLUSTRATOR': 'fas fa-pencil-alt',
    'XD': 'fab fa-adobe',
    'INVISION': 'fas fa-eye',
    'ZEPLIN': 'fas fa-ruler-combined',
    'FRAMER': 'fas fa-window-maximize',
    'UX_PIN': 'fas fa-drafting-compass',
    'PRINCIPLE': 'fas fa-bezier-curve',
    'AXURE': 'fas fa-sitemap',
    'PROTO_IO': 'fas fa-mobile-alt',

    # DevOps & Tools
    'LINUX': 'fab fa-linux',
    'UBUNTU': 'fab fa-ubuntu',
    'DEBIAN': 'fab fa-linux',
    'WINDOWS': 'fab fa-windows',
    'MACOS': 'fab fa-apple',
    'NPM': 'fab fa-npm',
    'YARN': 'fab fa-yarn',
    'GRADLE': 'fas fa-hammer',
    'MAVEN': 'fas fa-hammer',
    'ESLINT': 'fas fa-spell-check',
    'PRETTIER': 'fas fa-paint-brush',
    'TRAVIS': 'fas fa-check-circle',
    'CIRCLECI': 'fas fa-circle-notch',
    'SONARQUBE': 'fas fa-shield-alt',
    'GRAFANA': 'fas fa-chart-line',
    'PROMETHEUS': 'fas fa-fire',
    'ELASTIC': 'fas fa-search',
    'KIBANA': 'fas fa-chart-bar',
    'NEW_RELIC': 'fas fa-chart-line',
    'DATADOG': 'fas fa-dog',
    'SPLUNK': 'fas fa-search',
    'JIRA': 'fab fa-jira',
    'CONFLUENCE': 'fab fa-atlassian',
    'TRELLO': 'fab fa-trello',
    'ASANA': 'fas fa-tasks',
    'NOTION': 'fas fa-sticky-note',
    'POSTMAN': 'fas fa-paper-plane',
    'INSOMNIA': 'fas fa-moon',
    'HOMEBREW': 'fas fa-beer',
    'GRAYLOG': 'fas fa-clipboard-list',
    'SENTRY': 'fas fa-exclamation-triangle',
    'BAMBOO': 'fab fa-atlassian',
    'TEAMCITY': 'fas fa-people-carry',
    'VAULT': 'fas fa-lock',
    'CONSUL': 'fas fa-handshake',
    'VAGRANT': 'fas fa-box',
    'SNYK': 'fas fa-shield-alt',
    'CODEQL': 'fas fa-code',
    'SONATYPE': 'fas fa-box',

    # Data Science & AI
    'PANDAS': 'fas fa-table',
    'NUMPY': 'fas fa-calculator',
    'TENSORFLOW': 'fas fa-brain',
    'PYTORCH': 'fas fa-fire',
    'KERAS': 'fas fa-brain',
    'SCIKIT_LEARN': 'fas fa-cogs',
    'APACHE_SPARK': 'fas fa-bolt',
    'APACHE_AIRFLOW': 'fas fa-wind',
    'DASK': 'fas fa-layer-group',
    'JUPYTER': 'fas fa-book-open',
    'HADOOP': 'fas fa-database',
    'TABLEAU': 'fas fa-chart-bar',
    'POWER_BI': 'fas fa-chart-pie',
    'LOOKER': 'fas fa-search',
    'METABASE': 'fas fa-chart-line',
    'SUPERSET': 'fas fa-chart-area',
    'DPLYR': 'fas fa-filter',
    'MATPLOTLIB': 'fas fa-chart-line',
    'SEABORN': 'fas fa-chart-area',
    'PLOTLY': 'fas fa-chart-bar',
    'OPENCV': 'fas fa-eye',
    'HUGGINGFACE': 'fas fa-grin',
    'LANGCHAIN': 'fas fa-link',
    'OPENAI': 'fas fa-robot',
    'SPACY': 'fas fa-language',
    'NLTK': 'fas fa-comment',
    'GENSIM': 'fas fa-clone',

    # API & Communication
    'SOAP': 'fas fa-soap',
    'MQTT': 'fas fa-broadcast-tower',
    'WEBSOCKET': 'fas fa-plug',
    'WEBRTC': 'fas fa-video',
    'FASTCGI': 'fas fa-bolt',
    'ZEROMQ': 'fas fa-envelope',
    'NATS': 'fas fa-comments',
    'AMQP': 'fas fa-envelope-open-text',
    'STOMP': 'fas fa-hiking',
    'JSON_RPC': 'fas fa-exchange-alt',
    'XML_RPC': 'fas fa-exchange-alt',

    # Other
    'BLOCKCHAIN': 'fas fa-link',
    'WEB3': 'fab fa-ethereum',
    'IOT': 'fas fa-network-wired',
    'GAME_DEV': 'fas fa-gamepad',
    'UNITY': 'fab fa-unity',
    'UNREAL': 'fas fa-gamepad',
    'WEBGL': 'fas fa-cubes',
    'WEBASSEMBLY': 'fas fa-microchip',
    'PWA': 'fas fa-mobile',
    'JAM_STACK': 'fas fa-layer-group',
    'SERVERLESS': 'fas fa-cloud',
    'MICROSERVICES': 'fas fa-th',
    'EVENT_SOURCING': 'fas fa-stream',
    'CQRS': 'fas fa-object-group',
    'DDD': 'fas fa-project-diagram',
    'SOLID': 'fas fa-cube',
    'TDD': 'fas fa-vial',
    'BDD': 'fas fa-list',
    'CI_CD': 'fas fa-infinity',
    'AGILE': 'fas fa-running',
    'SCRUM': 'fas fa-users',
    'KANBAN': 'fas fa-clipboard',
    'DEVOPS': 'fas fa-cogs',
    'MLOPS': 'fas fa-cog',
    'DATAOPS': 'fas fa-database',
    'FINOPS': 'fas fa-dollar-sign',
    'GITOPS': 'fab fa-git-alt',

    # Default icon for any skill not listed
    'DEFAULT': 'fas fa-code'
}

# Brand colors for each skill
SKILL_COLORS = {
    'PYTHON': '#3776AB',
    'JAVASCRIPT': '#F7DF1E',
    'TYPESCRIPT': '#3178C6',
    'JAVA': '#007396',
    'CSHARP': '#239120',
    'CPP': '#00599C',
    'C': '#A8B9CC',
    'PHP': '#777BB4',
    'RUBY': '#CC342D',
    'GO': '#00ADD8',
    'RUST': '#CE412B',  # Changed from #000000
    'SWIFT': '#FA7343',
    'KOTLIN': '#7F52FF',
    'PERL': '#39457E',
    'SCALA': '#DC322F',
    'HASKELL': '#5D4F85',
    'LUA': '#000080',
    'R': '#276DC3',
    'JULIA': '#9558B2',
    'DART': '#0175C2',
    'ELIXIR': '#4B275F',
    'CLOJURE': '#5881D8',
    'ERLANG': '#A90533',
    'FORTRAN': '#4D41B1',
    'GROOVY': '#4298B8',
    'LISP': '#5C5C5C',
    'OBJECTIVEC': '#438EFF',
    'PASCAL': '#E3F171',
    'COBOL': '#005CA5',
    'ASSEMBLY': '#6E4C13',
    'MATLAB': '#BB92AC',
    'POWERSHELL': '#5391FE',
    'BASH': '#4EAA25',
    'VBNET': '#00539C',
    'VERILOG': '#848484',
    'VHDL': '#ADB2CB',
    'ABAP': '#E8A004',
    'ADA': '#02F88C',
    'SAS': '#0099D4',
    'SCHEME': '#1E4AEC',
    'SOLIDITY': '#363636',
    'SQL': '#E38C00',
    'ZIG': '#F7A41D',
    'CRYSTAL': '#000100',  # Changed from #000000
    'F_SHARP': '#378BBA',
    'VBA': '#867DB1',
    'DELPHI': '#EE1F35',
    'OCAML': '#EC6813',
    'PROLOG': '#74283C',
    'D': '#B03931',

    # ==== WEB FRAMEWORKS & LIBRARIES ====
    'DJANGO': '#092E20',
    'FLASK': '#25C2A0',  # Changed from #000000
    'FASTAPI': '#009688',
    'RAILS': '#CC0000',
    'SPRING': '#6DB33F',
    'LARAVEL': '#FF2D20',
    'SYMFONY': '#7A8288',  # Changed from #000000
    'EXPRESS': '#259DFF',  # Changed from #000000
    'ASPNET': '#512BD4',
    'ASPNET_MVC': '#0067CF',
    'ASPNET_CORE': '#68217A',
    'NESTJS': '#E0234E',
    'DOTNET': '#512BD4',
    'STRUTS': '#D6761C',
    'JSF': '#F8981D',
    'GIN': '#00ADD8',
    'ECHO': '#269539',
    'FIBER': '#00ACD7',
    'FLASK_RESTFUL': '#3F51B5',  # Indigo for REST frameworks
    'FALCON': '#00D1B2',  # Teal color similar to other Python frameworks
    'PHOENIX': '#FD4F00',
    'KOA': '#33333D',  # Dark color from Koa's theme
    'SINATRA': '#CF1725',
    'CATALYST': '#2E5387',  # Blue to represent catalytic nature
    'PLAY': '#92D13D',  # Green from Play Framework's logo
    'CakePHP': '#D33C43',
    'SLIM': '#2196F3',  # Blue similar to other PHP frameworks
    'ZEND': '#68B604',
    'TORNADO': '#1F1F1D',

	#  ==== FRONTEND FRAMEWORKS & LIBRARIES ====
    'REACT': '#61DAFB',
    'ANGULAR': '#DD0031',
    'VUEJS': '#4FC08D',
    'SVELTE': '#FF3E00',
    'NEXTJS': '#0070F3',  # Changed from #000000
    'NUXTJS': '#00DC82',
    'GATSBY': '#663399',
    'EMBER': '#E04E39',
    'BACKBONE': '#0071B5',
    'JQUERY': '#0769AD',
    'BOOTSTRAP': '#7952B3',
    'TAILWIND': '#38B2AC',
    'BULMA': '#00D1B2',
    'MATERIALIZE': '#EB7077',
    'FOUNDATION': '#14679E',
    'SEMANTIC_UI': '#35BDB2',
    'MATERIAL_UI': '#0081CB',
    'CHAKRA_UI': '#319795',
    'STYLED_COMPONENTS': '#DB7093',
    'EMOTION': '#D26AC2',
    'SASS': '#CC6699',
    'LESS': '#1D365D',
    'STYLUS': '#FF6347',
    'HTML': '#E34F26',
    'CSS': '#1572B6',
    'POSTCSS': '#DD3A0A',
    'REDUX': '#764ABC',
    'MOBX': '#FF9955',
    'RECOIL': '#3578E5',
    'ZUSTAND': '#F1C40F',
    'ALPINE': '#2D3741',  # Alpine's brand color
    'PREACT': '#673AB8',
    'LIT': '#324FFF',
    'STENCIL': '#4A46FF',
    'SOLID': '#2C4F7C',
    'STIMULUS': '#74D7FE',
    'STORYBOOK': '#FF4785',
    'D3': '#F9A03C',
    'CHART_JS': '#FF6384',
    'THREE_JS': '#049EF4',
    'GSAP': '#88CE02',
    'WEBPACK': '#8DD6F9',
    'VITE': '#646CFF',
    'ESBUILD': '#FFCF00',
    'PARCEL': '#CF4647',
    'ROLLUP': '#FF3333',
    'BABEL': '#F9DC3E',

    # ==== BACKEND & INFRASTRUCTURE ====
    'NODEJS': '#339933',
    'DENO': '#7B7B7B',  # Changed from #000000
    'BUNTJS': '#FB0790',
    'GRAPHQL': '#E10098',
    'APOLLO': '#311C87',
    'PRISMA': '#2D3748',
    'HASURA': '#1EB4D4',
    'REST': '#8BC34A',
    'GRPC': '#2DA6B0',
    'OAUTH': '#EB5424',
    'JWT': '#D63AFF',  # Changed from #000000
    'SWAGGER': '#85EA2D',
    'OPENAPI': '#3371E3',
    'RABBITMQ': '#FF6600',
    'KAFKA': '#231F20',
    'REDIS': '#DC382D',
    'CELERY': '#37814A',
    'SOCKET_IO': '#010101',
    'NGINX': '#009639',
    'APACHE': '#D22128',
    'CADDY': '#00ADD8',
    'TRAEFIK': '#24A1C1',
    'DOCKER': '#2496ED',
    'KUBERNETES': '#326CE5',
    'PODMAN': '#892CA0',
    'JENKINS': '#D24939',
    'TERRAFORM': '#7B42BC',
    'ANSIBLE': '#EE0000',
    'PUPPET': '#FFAE1A',
    'CHEF': '#F38C00',
    'PULUMI': '#8A3391',

    # ==== CLOUD PLATFORMS & SERVICES ====
    'AWS': '#FF9900',
    'AZURE': '#0078D4',
    'GCP': '#4285F4',
    'HEROKU': '#430098',
    'DIGITALOCEAN': '#0080FF',
    'VERCEL': '#5F6368',  # Changed from #000000
    'NETLIFY': '#00C7B7',
    'FIREBASE': '#FFCA28',
    'CLOUDFLARE': '#F38020',
    'LINODE': '#00A95C',
    'ORACLE_CLOUD': '#F80000',
    'IBM_CLOUD': '#1261FE',
    'OPENSTACK': '#ED1944',
    'LAMBDA': '#FF9900',
    'S3': '#569A31',
    'EC2': '#FF9900',
    'RDS': '#527FFF',
    'CLOUDFRONT': '#8C4FFF',
    'DYNAMODB': '#4053D6',
    'ECS': '#FF9900',
    'EKS': '#FF9900',
    'IAM': '#FF9900',
    'ROUTE53': '#FF9900',
    'AZURE_FUNCTIONS': '#0062AD',
    'AZURE_DEVOPS': '#0078D7',
    'COSMOS_DB': '#3A96DD',
    'APP_ENGINE': '#4285F4',
    'CLOUD_FUNCTIONS': '#4285F4',
    'BIG_QUERY': '#4285F4',
    'CLOUD_STORAGE': '#4285F4',
    'AUTH0': '#EB5424',
    'SUPABASE': '#3ECF8E',

    # ==== DATABASES ====
    'MYSQL': '#4479A1',
    'POSTGRESQL': '#4169E1',
    'MONGODB': '#47A248',
    'SQLITE': '#003B57',
    'CASSANDRA': '#1287B1',
    'MARIADB': '#003545',
    'ELASTICSEARCH': '#005571',
    'COUCHDB': '#E42528',
    'NEO4J': '#018BFF',
    'MICROSOFT_SQL': '#CC2927',
    'ORACLE_DB': '#F80000',
    'INFLUXDB': '#22ADF6',
    'FIRESTORE': '#FFCA28',
    'REALM': '#39477F',
    'DGRAPH': '#E50695',
    'COCKROACHDB': '#6933FF',
    'TIMESCALE': '#FDB515',
    'SNOWFLAKE': '#29B5E8',
    'CLICKHOUSE': '#FFCC01',
    'SURREALDB': '#FF00A0',
    'FAUNA': '#3813DF',
    'PLANETSCALE': '#316BD9',
    'REDIS_DB': '#DC382D',
    'MEMCACHED': '#1E90FF',
    'SCYLLADB': '#4B5FF7',
    'APPWRITE': '#F02E65',
    'DATOMIC': '#66CDAA',
    'IBMDB2': '#1F70C1',

    # ==== VERSION CONTROL ====
    'GIT': '#F05032',
    'GITHUB': '#181717',
    'GITHUB_ACTIONS': '#2088FF',
    'GITLAB': '#FC6D26',
    'BITBUCKET': '#0052CC',
    'MERCURIAL': '#999999',
    'SVN': '#809CC9',
    'PERFORCE': '#40347A',
    'TFS': '#0078D7',

    # ==== TESTING ====
    'JEST': '#C21325',
    'MOCHA': '#8D6748',
    'SELENIUM': '#43B02A',
    'CYPRESS': '#17202C',
    'JUNIT': '#25A162',
    'PHPUNIT': '#3C9CD7',
    'PYTEST': '#0A9EDC',
    'JASMINE': '#8A4182',
    'KARMA': '#429F87',
    'TESTNG': '#44CB65',
    'MOCKITO': '#88B250',
    'PLAYWRIGHT': '#2EAD33',
    'PUPPETEER': '#00D8A2',
    'WEBDRIVERIO': '#EA5906',
    'VITEST': '#729B1B',
    'CUCUMBER': '#23D96C',
    'NIGHTWATCH': '#6F205A',
    'STORYBOOK_TEST': '#FF4785',
    'TESTING_LIBRARY': '#E33332',
    'CHAI': '#A30701',
    'ENZYME': '#813F95',

    # ==== MOBILE DEVELOPMENT ====
    'ANDROID': '#3DDC84',
    'IOS': '#007AFF',  # Changed from #000000
    'REACTNATIVE': '#61DAFB',
    'FLUTTER': '#02569B',
    'IONIC': '#3880FF',
    'XAMARIN': '#3498DB',
    'CORDOVA': '#4CC2E4',
    'CAPACITOR': '#119EFF',
    'NATIVESCRIPT': '#65ADF1',
    'UNO_PLATFORM': '#212121',
    'MAUI': '#5C2D91',
    'SWIFT_UI': '#F05138',
    'JETPACK_COMPOSE': '#4285F4',
    'KOTLIN_MULTIPLATFORM': '#7F52FF',
    'TAURI': '#FFC131',

    #  ==== CMS & ECOMMERCE ====
    'WORDPRESS': '#21759B',
    'DRUPAL': '#0678BE',
    'JOOMLA': '#5091CD',
    'MAGENTO': '#EE672F',
    'SHOPIFY': '#7AB55C',
    'WOOCOMMERCE': '#96588A',
    'CONTENTFUL': '#3B80CE',
    'STRAPI': '#8E75FF',
    'GHOST': '#15171A',
    'SANITY': '#F03E2F',
    'WIXCMS': '#0C6EFC',
    'SQUARESPACE': '#5C6AC4',  # Changed from #000000
    'PRESTASHOP': '#DF0067',
    'OPENCART': '#26B9E1',
    'WEBFLOW': '#4353FF',
    'BIGCOMMERCE': '#121118',
    'SHOPWARE': '#189EFF',

    # ==== DESIGN & UI/UX ====
    'FIGMA': '#F24E1E',
    'SKETCH': '#FDB300',
    'ADOBE': '#FF0000',
    'PHOTOSHOP': '#31A8FF',
    'ILLUSTRATOR': '#FF9A00',
    'XD': '#FF61F6',
    'INVISION': '#FF3366',
    'ZEPLIN': '#FDBD39',
    'FRAMER': '#0055FF',
    'UX_PIN': '#2A2F36',
    'PRINCIPLE': '#0330D1',
    'AXURE': '#0099CC',
    'PROTO_IO': '#34A7FF',

    # ==== DevOps & TOOLS ====
    'LINUX': '#FCC624',
    'UBUNTU': '#E95420',
    'DEBIAN': '#A81D33',
    'WINDOWS': '#0078D6',
    'MACOS': '#999999',  # Changed from #000000
    'NPM': '#CB3837',
    'YARN': '#2C8EBB',
    'GRADLE': '#02303A',
    'MAVEN': '#C71A36',
    'ESLINT': '#4B32C3',
    'PRETTIER': '#F7B93E',
    'TRAVIS': '#3EAAAF',
    'CIRCLECI': '#343434',
    'SONARQUBE': '#4E9BCD',
    'GRAFANA': '#F46800',
    'PROMETHEUS': '#E6522C',
    'ELASTIC': '#005571',
    'KIBANA': '#00BFB3',
    'NEW_RELIC': '#008C99',
    'DATADOG': '#632CA6',
    'SPLUNK': '#FF375F',  # Changed from #000000
    'JIRA': '#0052CC',
    'CONFLUENCE': '#0052CC',
    'TRELLO': '#0079BF',
    'ASANA': '#FC636B',
    'NOTION': '#37352F',  # Changed from #000000
    'POSTMAN': '#FF6C37',
    'INSOMNIA': '#4000BF',
    'HOMEBREW': '#FBB040',
    'GRAYLOG': '#FF3633',
    'SENTRY': '#362D59',
    'BAMBOO': '#0052CC',
    'TEAMCITY': '#0CB0F2',  # Changed from #000000
    'VAULT': '#2E84CC',  # Changed from #000000
    'CONSUL': '#F24C53',
    'VAGRANT': '#1563FF',
    'SNYK': '#4C4A73',
    'CODEQL': '#2088FF',
    'SONATYPE': '#1F2555',

    # ==== DATA SCIENCE & AI ====
    'PANDAS': '#150458',
    'NUMPY': '#013243',
    'TENSORFLOW': '#FF6F00',
    'PYTORCH': '#EE4C2C',
    'KERAS': '#D00000',
    'SCIKIT_LEARN': '#F7931E',
    'APACHE_SPARK': '#E25A1C',
    'APACHE_AIRFLOW': '#017CEE',
    'DASK': '#FD9827',
    'JUPYTER': '#F37626',
    'HADOOP': '#66CCFF',
    'TABLEAU': '#E97627',
    'POWER_BI': '#F2C811',
    'LOOKER': '#4285F4',
    'METABASE': '#509EE3',
    'SUPERSET': '#00A699',
    'DPLYR': '#1F77B4',
    'MATPLOTLIB': '#11557C',
    'SEABORN': '#3776AB',
    'PLOTLY': '#3F4F75',
    'OPENCV': '#5C3EE8',
    'HUGGINGFACE': '#FFD21E',
    'LANGCHAIN': '#00FFFF',
    'OPENAI': '#412991',
    'SPACY': '#09A3D5',
    'NLTK': '#154360',
    'GENSIM': '#E74C3C',

    # ==== API & Communication ====
    'SOAP': '#78909C',  # Blue-gray for legacy protocols
    'MQTT': '#660066',
    'WEBSOCKET': '#1976D2',  # Blue for real-time protocols
    'WEBRTC': '#333333',
    'FASTCGI': '#2196F3',  # Blue for web protocols
    'ZEROMQ': '#DF0000',
    'NATS': '#34A574',
    'AMQP': '#FF6600',
    'STOMP': '#48B0F7',  # Changed from #000000
    'JSON_RPC': '#795548',  # Brown for RPC protocols
    'XML_RPC': '#795548',  # Brown for RPC protocols

    # ==== Other ====
    'BLOCKCHAIN': '#121D33',
    'WEB3': '#F16822',
    'IOT': '#03A9F4',  # Light blue for connected devices
    'GAME_DEV': '#E91E63',  # Pink for gaming
    'UNITY': '#4B4B4B',  # Changed from #000000
    'UNREAL': '#0E1128',
    'WEBGL': '#990000',
    'WEBASSEMBLY': '#654FF0',
    'PWA': '#7B1FA2',  # Purple for progressive apps
    'JAM_STACK': '#4A148C',  # Deep purple for modern web stack
    'SERVERLESS': '#FF9800',  # Orange for cloud functions
    'MICROSERVICES': '#3F51B5',  # Indigo for service architecture
    'EVENT_SOURCING': '#9C27B0',  # Purple for event streams
    'CQRS': '#607D8B',  # Blue-gray for architecture patterns
    'DDD': '#FF5722',  # Deep orange for domain depth
    'SOLID': '#2196F3',
    'TDD': '#4CAF50',
    'BDD': '#FF5722',
    'CI_CD': '#4CAF50',  # Green to represent continuous flow
    'AGILE': '#7952B3',  # Purple to represent adaptability
    'SCRUM': '#795548',
    'KANBAN': '#E91E63',
    'DEVOPS': '#00BCD4',
    'MLOPS': '#673AB7',  # Deep purple for ML operations
    'DATAOPS': '#00BCD4',  # Cyan for data operations
    'FINOPS': '#FFC107',  # Amber for financial operations
    'GITOPS': '#F44336',  # Red for Git operations
}

# Default icon for skills not in the mapping
DEFAULT_ICON = 'fas fa-code'
DEFAULT_COLOR = '#6c757d'  # A neutral gray color

def get_skill_icon(skill_code):
    """Get the Font Awesome icon class for a skill code"""
    return SKILL_ICONS.get(skill_code.upper(), DEFAULT_ICON)

def get_skill_color(skill_code):
    """Get the brand color for a skill code"""
    if skill_code is None:
        return DEFAULT_COLOR

    if isinstance(skill_code, str):
        return SKILL_COLORS.get(skill_code.upper(), DEFAULT_COLOR)

    return DEFAULT_COLOR

def get_skill_display(skill_code):
    """Get the display name for a skill code"""
    for code, name in SKILL_CHOICES:
        if code == skill_code.upper():
            return name
    return skill_code
