# Dictionary of available skills and their corresponding Font Awesome icons
SKILL_CHOICES = [
    ('PYTHON', 'Python'),
    ('DJANGO', 'Django'),
    ('FLASK', 'Flask'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('JAVASCRIPT', 'JavaScript'),
    ('TYPESCRIPT', 'TypeScript'),
    ('REACT', 'React'),
    ('NEXTJS', 'Next.js'),
    ('VUEJS', 'Vue.js'),
    ('NUXTJS', 'Nuxt.js'),
    ('ANGULAR', 'Angular'),
    ('SVELTE', 'Svelte'),
    ('NODEJS', 'Node.js'),
    ('EXPRESS', 'Express'),
    ('PHP', 'PHP'),
    ('LARAVEL', 'Laravel'),
    ('SYMFONY', 'Symfony'),
    ('JAVA', 'Java'),
    ('SPRING', 'Spring'),
    ('KOTLIN', 'Kotlin'),
    ('SWIFT', 'Swift'),
    ('CSHARP', 'C#'),
    ('DOTNET', '.NET'),
    ('RUBY', 'Ruby'),
    ('RAILS', 'Ruby on Rails'),
    ('GO', 'Go'),
    ('RUST', 'Rust'),
    ('DOCKER', 'Docker'),
    ('KUBERNETES', 'Kubernetes'),
    ('GIT', 'Git'),
    ('GITHUB', 'GitHub'),
    ('GITLAB', 'GitLab'),
    ('BITBUCKET', 'Bitbucket'),
    ('AWS', 'AWS'),
    ('AZURE', 'Azure'),
    ('GCP', 'Google Cloud'),
    ('DIGITALOCEAN', 'DigitalOcean'),
    ('HEROKU', 'Heroku'),
    ('NETLIFY', 'Netlify'),
    ('NGINX', 'Nginx'),
    ('APACHE', 'Apache'),
    ('MYSQL', 'MySQL'),
    ('POSTGRESQL', 'PostgreSQL'),
    ('MONGODB', 'MongoDB'),
    ('REDIS', 'Redis'),
    ('ELASTICSEARCH', 'Elasticsearch'),
    ('GRAPHQL', 'GraphQL'),
    ('LINUX', 'Linux'),
    ('UBUNTU', 'Ubuntu'),
    ('WINDOWS', 'Windows'),
    ('MACOS', 'macOS'),
    ('ANDROID', 'Android'),
    ('IOS', 'iOS'),
    ('FLUTTER', 'Flutter'),
    ('REACT_NATIVE', 'React Native'),
    ('WORDPRESS', 'WordPress'),
    ('DRUPAL', 'Drupal'),
    ('BOOTSTRAP', 'Bootstrap'),
    ('TAILWIND', 'Tailwind CSS'),
    ('SASS', 'Sass'),
    ('WEBPACK', 'Webpack'),
    ('BABEL', 'Babel'),
    ('NPM', 'npm'),
    ('YARN', 'Yarn'),
    ('JENKINS', 'Jenkins'),
    ('TRAVIS', 'Travis CI'),
    ('CIRCLECI', 'CircleCI'),
    ('ANSIBLE', 'Ansible'),
    ('TERRAFORM', 'Terraform'),
    ('JIRA', 'Jira'),
    ('TRELLO', 'Trello'),
    ('FIGMA', 'Figma'),
    ('PHOTOSHOP', 'Photoshop'),
    ('ILLUSTRATOR', 'Illustrator'),
    ('JEST', 'Jest'),
    ('CYPRESS', 'Cypress'),
    ('SELENIUM', 'Selenium'),
    ('PYTORCH', 'PyTorch'),
    ('TENSORFLOW', 'TensorFlow'),
]

# Dictionary mapping skill codes to their Font Awesome icons
SKILL_ICONS = {
    'PYTHON': 'fab fa-python',
    'DJANGO': 'fab fa-python',
    'FLASK': 'fab fa-python',
    'HTML': 'fab fa-html5',
    'CSS': 'fab fa-css3-alt',
    'JAVASCRIPT': 'fab fa-js',
    'TYPESCRIPT': 'fab fa-js',
    'REACT': 'fab fa-react',
    'NEXTJS': 'fab fa-react',
    'VUEJS': 'fab fa-vuejs',
    'NUXTJS': 'fab fa-vuejs',
    'ANGULAR': 'fab fa-angular',
    'SVELTE': 'fas fa-code',
    'NODEJS': 'fab fa-node-js',
    'EXPRESS': 'fab fa-node-js',
    'PHP': 'fab fa-php',
    'LARAVEL': 'fab fa-laravel',
    'SYMFONY': 'fab fa-symfony',
    'JAVA': 'fab fa-java',
    'SPRING': 'fas fa-leaf',
    'KOTLIN': 'fab fa-android',
    'SWIFT': 'fab fa-swift',
    'CSHARP': 'fab fa-microsoft',
    'DOTNET': 'fab fa-microsoft',
    'RUBY': 'fas fa-gem',
    'RAILS': 'fas fa-train',
    'GO': 'fas fa-circle',
    'RUST': 'fas fa-cog',
    'DOCKER': 'fab fa-docker',
    'KUBERNETES': 'fas fa-dharmachakra',
    'GIT': 'fab fa-git-alt',
    'GITHUB': 'fab fa-github',
    'GITLAB': 'fab fa-gitlab',
    'BITBUCKET': 'fab fa-bitbucket',
    'AWS': 'fab fa-aws',
    'AZURE': 'fab fa-microsoft',
    'GCP': 'fab fa-google',
    'DIGITALOCEAN': 'fab fa-digital-ocean',
    'HEROKU': 'fas fa-cloud',
    'NETLIFY': 'fas fa-cloud-upload-alt',
    'NGINX': 'fas fa-server',
    'APACHE': 'fas fa-server',
    'MYSQL': 'fas fa-database',
    'POSTGRESQL': 'fas fa-database',
    'MONGODB': 'fas fa-leaf',
    'REDIS': 'fas fa-database',
    'ELASTICSEARCH': 'fas fa-search',
    'GRAPHQL': 'fas fa-project-diagram',
    'LINUX': 'fab fa-linux',
    'UBUNTU': 'fab fa-ubuntu',
    'WINDOWS': 'fab fa-windows',
    'MACOS': 'fab fa-apple',
    'ANDROID': 'fab fa-android',
    'IOS': 'fab fa-apple',
    'FLUTTER': 'fas fa-mobile-alt',
    'REACT_NATIVE': 'fab fa-react',
    'WORDPRESS': 'fab fa-wordpress',
    'DRUPAL': 'fab fa-drupal',
    'BOOTSTRAP': 'fab fa-bootstrap',
    'TAILWIND': 'fab fa-css3',
    'SASS': 'fab fa-sass',
    'WEBPACK': 'fas fa-box-open',
    'BABEL': 'fas fa-boxes',
    'NPM': 'fab fa-npm',
    'YARN': 'fab fa-yarn',
    'JENKINS': 'fab fa-jenkins',
    'TRAVIS': 'fas fa-check-circle',
    'CIRCLECI': 'fas fa-circle-notch',
    'ANSIBLE': 'fas fa-terminal',
    'TERRAFORM': 'fas fa-cubes',
    'JIRA': 'fab fa-jira',
    'TRELLO': 'fab fa-trello',
    'FIGMA': 'fab fa-figma',
    'PHOTOSHOP': 'fas fa-paint-brush',
    'ILLUSTRATOR': 'fas fa-pencil-alt',
    'JEST': 'fas fa-vial',
    'CYPRESS': 'fas fa-check-double',
    'SELENIUM': 'fas fa-robot',
    'PYTORCH': 'fas fa-fire',
    'TENSORFLOW': 'fas fa-brain',
}

# Brand colors for each skill
SKILL_COLORS = {
    'PYTHON': '#3776AB',
    'DJANGO': '#092E20',
    'FLASK': '#000000',
    'HTML': '#E34F26',
    'CSS': '#1572B6',
    'JAVASCRIPT': '#F7DF1E',
    'TYPESCRIPT': '#3178C6',
    'REACT': '#61DAFB',
    'NEXTJS': '#000000',
    'VUEJS': '#4FC08D',
    'NUXTJS': '#00DC82',
    'ANGULAR': '#DD0031',
    'SVELTE': '#FF3E00',
    'NODEJS': '#339933',
    'EXPRESS': '#000000',
    'PHP': '#777BB4',
    'LARAVEL': '#FF2D20',
    'SYMFONY': '#000000',
    'JAVA': '#007396',
    'SPRING': '#6DB33F',
    'KOTLIN': '#7F52FF',
    'SWIFT': '#FA7343',
    'CSHARP': '#239120',
    'DOTNET': '#512BD4',
    'RUBY': '#CC342D',
    'RAILS': '#CC0000',
    'GO': '#00ADD8',
    'RUST': '#000000',
    'DOCKER': '#2496ED',
    'KUBERNETES': '#326CE5',
    'GIT': '#F05032',
    'GITHUB': '#181717',
    'GITLAB': '#FC6D26',
    'BITBUCKET': '#0052CC',
    'AWS': '#FF9900',
    'AZURE': '#0078D4',
    'GCP': '#4285F4',
    'DIGITALOCEAN': '#0080FF',
    'HEROKU': '#430098',
    'NETLIFY': '#00C7B7',
    'NGINX': '#009639',
    'APACHE': '#D22128',
    'MYSQL': '#4479A1',
    'POSTGRESQL': '#4169E1',
    'MONGODB': '#47A248',
    'REDIS': '#DC382D',
    'ELASTICSEARCH': '#005571',
    'GRAPHQL': '#E10098',
    'LINUX': '#FCC624',
    'UBUNTU': '#E95420',
    'WINDOWS': '#0078D6',
    'MACOS': '#000000',
    'ANDROID': '#3DDC84',
    'IOS': '#000000',
    'FLUTTER': '#02569B',
    'REACT_NATIVE': '#61DAFB',
    'WORDPRESS': '#21759B',
    'DRUPAL': '#0678BE',
    'BOOTSTRAP': '#7952B3',
    'TAILWIND': '#38B2AC',
    'SASS': '#CC6699',
    'WEBPACK': '#8DD6F9',
    'BABEL': '#F9DC3E',
    'NPM': '#CB3837',
    'YARN': '#2C8EBB',
    'JENKINS': '#D24939',
    'TRAVIS': '#3EAAAF',
    'CIRCLECI': '#343434',
    'ANSIBLE': '#EE0000',
    'TERRAFORM': '#7B42BC',
    'JIRA': '#0052CC',
    'TRELLO': '#0079BF',
    'FIGMA': '#F24E1E',
    'PHOTOSHOP': '#31A8FF',
    'ILLUSTRATOR': '#FF9A00',
    'JEST': '#C21325',
    'CYPRESS': '#17202C',
    'SELENIUM': '#43B02A',
    'PYTORCH': '#EE4C2C',
    'TENSORFLOW': '#FF6F00',
}

# Default icon for skills not in the mapping
DEFAULT_ICON = 'fas fa-code'
DEFAULT_COLOR = '#6c757d'  # A neutral gray color

def get_skill_icon(skill_code):
    """Get the Font Awesome icon class for a skill code"""
    return SKILL_ICONS.get(skill_code.upper(), DEFAULT_ICON)

def get_skill_color(skill_code):
    """Get the brand color for a skill code"""
    return SKILL_COLORS.get(skill_code.upper(), DEFAULT_COLOR)

def get_skill_display(skill_code):
    """Get the display name for a skill code"""
    for code, name in SKILL_CHOICES:
        if code == skill_code.upper():
            return name
    return skill_code
