# Generated by Django 5.1.6 on 2025-02-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('PARIS', 'Paris'), ('LILLE', 'Lille'), ('TOULOUSE', 'Toulouse'), ('NICE', 'Nice')], default='PARIS', max_length=20, verbose_name='Campus'),
        ),
    ]
