# Generated by Django 5.1.6 on 2025-02-14 14:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(blank=True, help_text='Entrez le nom de votre campus', max_length=100, verbose_name='Campus'),
        ),
    ]
