# Generated by Django 5.1.6 on 2025-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('FOND', 'Fondamentaux'), ('CYBER', 'Cybersécurité'), ('AI', 'Intelligence Artificielle'), ('ARVR', 'AR/VR'), ('BLOCK', 'BlockChaine'), ('WEB', 'Web FullStack')], max_length=5),
        ),
    ]
