# Generated by Django 5.1.6 on 2025-02-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
