# Generated by Django 5.1.6 on 2025-02-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_coordinates',
            field=models.CharField(blank=True, help_text='Format: latitude,longitude (ex: 48.8566,2.3522)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.CharField(blank=True, help_text="Ville ou adresse complète de l'entreprise", max_length=255),
        ),
    ]
