# Generated by Django 5.1.6 on 2025-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_company_coordinates_user_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
