# Generated by Django 5.1.6 on 2025-02-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dev_to_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gitlab_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medium_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
