# Generated by Django 4.2.7 on 2025-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skills_known',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of skills the user knows and can teach'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills_to_learn',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of skills the user wants to learn'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated list of skills (deprecated)'),
        ),
    ]
