# Generated by Django 4.2.7 on 2025-03-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_skills_known_customuser_skills_to_learn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='devto_url',
            field=models.URLField(blank=True, verbose_name='Dev.to URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Discord Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mastodon_url',
            field=models.URLField(blank=True, verbose_name='Mastodon URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medium_url',
            field=models.URLField(blank=True, verbose_name='Medium URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stackoverflow_url',
            field=models.URLField(blank=True, verbose_name='Stack Overflow URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitch_url',
            field=models.URLField(blank=True, verbose_name='Twitch URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter/X URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
    ]
